// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrL0IGcLpU9K2SPLkIWRuVE7KRsjd_Df0',
    appId: '1:1020671239792:web:edf3115172d51e869f76b5',
    messagingSenderId: '1020671239792',
    projectId: 'vossa4tefa',
    authDomain: 'vossa4tefa.firebaseapp.com',
    databaseURL: 'https://vossa4tefa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vossa4tefa.firebasestorage.app',
    measurementId: 'G-55E80LXWYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBokvn8siwW11KOxqc3bWb6-M_zRZbWEao',
    appId: '1:1020671239792:android:b29448c94eb79ca59f76b5',
    messagingSenderId: '1020671239792',
    projectId: 'vossa4tefa',
    databaseURL: 'https://vossa4tefa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vossa4tefa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIbKf-TatMPfo05l0Nkwn3fRpJRmCkli0',
    appId: '1:1020671239792:ios:2692f2b368be0ff99f76b5',
    messagingSenderId: '1020671239792',
    projectId: 'vossa4tefa',
    databaseURL: 'https://vossa4tefa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vossa4tefa.firebasestorage.app',
    iosBundleId: 'com.example.softSkillsTefa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIbKf-TatMPfo05l0Nkwn3fRpJRmCkli0',
    appId: '1:1020671239792:ios:2692f2b368be0ff99f76b5',
    messagingSenderId: '1020671239792',
    projectId: 'vossa4tefa',
    databaseURL: 'https://vossa4tefa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vossa4tefa.firebasestorage.app',
    iosBundleId: 'com.example.softSkillsTefa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrL0IGcLpU9K2SPLkIWRuVE7KRsjd_Df0',
    appId: '1:1020671239792:web:e5f349b936ec47819f76b5',
    messagingSenderId: '1020671239792',
    projectId: 'vossa4tefa',
    authDomain: 'vossa4tefa.firebaseapp.com',
    databaseURL: 'https://vossa4tefa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vossa4tefa.firebasestorage.app',
    measurementId: 'G-W7GTS4P7WC',
  );
}
